name: plugin-build
run-name: Building plugin
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ZorshDeltarune-1.0-all
          path: build/libs/ZorshDeltarune-1.0-all.jar
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ZorshDeltarune-1.0-all
          path: downloaded_artifact/
      
      - name: Deploy to test server
        uses: sand4rt/ftp-deployer@v1.10
        with:
          sftp: true
          host: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          remote_folder: plugins
          local_folder: downloaded_artifact
          cleanup: false
          include: '["ZorshDeltarune-1.0-all.jar"]'
          exclude: '[]'
          passive: true
  notify:
    needs: [deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: '[{"title": "Project deployed to the test server","description": "**Latest commit:**\n${{ github.event.head_commit.message }}"}]'
        uses: Ilshidur/action-discord@ad5235de713df3ef38022185499b02ffe93b7efe
        with:
          args: '{{ EVENT_PAYLOAD.repository.full_name }} has been deployed'
